apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-service
  template:
    metadata:
      labels:
        app: metadata-service
    spec:
      containers:
        - name: metadata-service
          image: metadata-service:dev
          ports:
            - containerPort: 5299
          env:
            - name: ConnectionStrings__Default
              value: "Host=postgres;Port=5432;Database=metadata_service_db;Username=meteorcloud;Password=secretpassword"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"