apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      initContainers:
        - name: wait-for-deps
          image: busybox
          command: [ 'sh', '-c', '
            until nc -z postgres 5432 && nc -z rabbitmq 5672 && nc -z redis 6379;
            do echo waiting for dependencies; sleep 2; done;
          ' ]
      containers:
        - name: notification-service
          image: notification-service:dev
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__Default
              value: "Host=postgres;Port=5432;Database=notification_service_db;Username=meteorcloud;Password=secretpassword"
            - name: SMTP_HOST
              value: "mailhog"
            - name: SMTP_PORT
              value: "1025"
            - name: SMTP_USERNAME
              value: ""
            - name: SMTP_PASSWORD
              value: ""
            - name: SMTP_FROM
              value: "no-reply@meteorcloud.com"
            - name: SMTP_ENABLE_SSL
              value: "false"
            - name: USER_SERVICE_URL
              value: http://user-service
            - name: WORKSPACE_SERVICE_URL
              value: http://workspace-service
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m