apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meteorcloud-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/user(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 80
          - path: /api/auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /api/file(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: file-service
                port:
                  number: 80
          - path: /api/workspace(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: workspace-service
                port:
                  number: 80
          - path: /api/notification(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 80
          - path: /api/metadata(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: metadata-service
                port:
                  number: 80
          - path: /api/link(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: link-service
                port:
                  number: 80
          - path: /api/audit(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: audit-service
                port:
                  number: 80