apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace-service
  template:
    metadata:
      labels:
        app: workspace-service
    spec:
      containers:
        - name: workspace-service
          image: workspace-service:dev
          ports:
            - containerPort: 5297
          env:
            - name: ConnectionStrings__Default
              value: "Host=postgres;Port=5432;Database=workspace_service_db;Username=meteorcloud;Password=secretpassword"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"