apiVersion: v1
kind: Service
metadata:
  name: azurite
spec:
  selector:
    app: azurite
  ports:
    - name: blob
      port: 10000
      targetPort: 10000
    - name: queue
      port: 10001
      targetPort: 10001
    - name: table
      port: 10002
      targetPort: 10002