apiVersion: apps/v1
kind: Deployment
metadata:
  name: link-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: link-service
  template:
    metadata:
      labels:
        app: link-service
    spec:
      containers:
        - name: link-service
          image: link-service:dev
          ports:
            - containerPort: 5301
          env:
            - name: ConnectionStrings__Default
              value: "Host=postgres;Port=5432;Database=link_service_db;Username=meteorcloud;Password=secretpassword"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"